name: organix
favicon: null
layout_spectrum: 0.9000709119718522
typography_spectrum: 0.2895259438082576
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.29798680543899536
  lightness: 0.5442635270301253
  saturation: 0.9182857170235366
  rhythmicContrast: 0.6286057794932276
purpose: []
